### ISSUE TITLE
Parallel sessions logging to same logger

### ISSUE THREAD

**Issue by sclewis23** [johnmyleswhite/log4r#14]
I'm running some API pulls in parallel (using multiple sessions) and trying to log all to one file appender.  It seems to work most of the time but when I have high number of writes about the same time some logs are partial.
I was wondering if you had some suggestions or is it possible to use locking?

**Comment by atheriel** [comment]
It is [not generally safe](https://stackoverflow.com/a/7892784/) on to have two processes write to the same file at the same time if the processes in question do any buffering -- which R does. I can think of a few alternatives:

1. Write to one file per session and then have your main process combine the files. Unless your logs are enormous this will probably be the easiest option. Since you're running tasks in parallel there is no guaranteed order to the logs anyway.

2. Write to something that handles multiple streams, such as [syslog](https://github.com/johnmyleswhite/log4r/blob/batteries-included/R/appenders.R#L156-L179) or a [socket](https://github.com/johnmyleswhite/log4r/blob/batteries-included/R/appenders.R#L73-L85). As you can guess from those links, direct support for this might be added to the package itself in the future.

Locking doesn't seem like a good alternative, since it would remove the advantage of doing things in parallel.

**Comment by sclewis23** [comment]
Yes, I think writing to separate logs ....is probably the best idea for now....maybe TCP logging might be something to think about later.  Thank you
